version: "3.9" # Specify a compatible version

services:
  db:
    image: postgres:14 # Use PostgreSQL 14
    environment:
      POSTGRES_USER: mucha
      POSTGRES_PASSWORD: mucha
      POSTGRES_DB: landmarks_backend_development # Set the database name
    volumes:
      - ./postgres-data:/var/lib/postgresql/data # Optional: Persistent data storage

  app:
    build: . # Build from the Dockerfile in the current directory
    ports:
      - "3000:3000" # Map container port 3000 to host port 3000
    depends_on:
      - db # Ensure database starts first
    environment:
      DATABASE_HOST: db
      DATABASE_USER: mucha
      DATABASE_PASSWORD: mucha

command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:create db:migrate db:seed && bundle exec rails server -b '0.0.0.0'"
